### PR TITLE
Backport latest changes from Z8

### PR DESCRIPTION
**Pull request by ktonga**
It includes changes from the following commits affecting the module
`effect` in the scalaz/scalaz repository:

- scalaz/scalaz@cf6ae80e3 fix bug in par and general code cleanup
- scalaz/scalaz@2f6c3dcae code cleanup
- scalaz/scalaz@a38e2b634 scalafmt
- scalaz/scalaz@d07918ba5 wrap up error model refactoring & update tests
- scalaz/scalaz@37c3e92a2 improved docs, function names, and bug fixes
- scalaz/scalaz@43e5f0a00 fixes #1665

### CODE REVIEW

**Review by fommil — APPROVED** [review]
I don't actually know this codebase very well, I've just been doing devops, but I'm :100: for backporting fixes from the scalaz8 line.

If you want to send a PR to align the scalafmt / scalafix with what is used in scalaz8 that's fine.

**Comment by fommil** [comment]
failure in the 2.11 backport

```
[info] Compiling 1 Scala source to /home/travis/build/scalaz/ioeffect/cats/target/scala-2.11/classes ...
[error] /home/travis/build/scalaz/ioeffect/ioeffect/src/test/scala/scalaz/ioeffect/RTSTest.scala:387:35: type mismatch;
[error]  found   : () => Unit
[error]  required: java.util.concurrent.Callable[Unit]
[error]         val _ = e.submit[Unit](() => cb(ExitResult.Completed(1)))
[error]                                   ^
[info] () => Unit <: java.util.concurrent.Callable[Unit]?
```

**Comment by ktonga** [comment]
Yeah, I saw that error, didn't try cross building locally. Will take a look later.

**Comment by fommil** [comment]
@ktonga I can push out a release whenever you want, but you said there was a transient failure on your machine so it would be good if we fix that first

**Pull request merged**
