### PR TITLE
invariant case object encoding

### LINKED ISSUE #8: use the scalaz-core encoding of invariant case objects
we don't need to use `Nothing` here, we have an encoding for this, see `INil` in the 7.3 branch.

```
private final case object Later extends AsyncReturn[Nothing]
```

https://github.com/scalaz/effect/blob/master/ioeffect/src/main/scala/scalaz/ioeffect/AsyncReturn.scala#L26

Also we can then do an exhaustive match instead of the `case _ => ` I see :scream:

### PR DESCRIPTION
**Pull request by fommil**
close #8

### CODE REVIEW

**Comment by fommil** [comment]
huh, I don't understand why this is failing the tests... this works in `scalaz-core`. Unless we are missing test coverage there

**Comment by fommil** [comment]
@xuwei-k any ideas why this fails?

**Comment by fommil** [comment]
nevermind, I found the problem. It's an unsafe cast elsewhere!

**Comment by fommil** [comment]
@jdegoes encoding you may not have been aware of ^^^

**Comment by fommil** [comment]
(I think we can easily create a compiler plugin that does this optimisation automatically)

**Review by S11001001 — APPROVED** [review]

**Comment by jdegoes** [comment]
@fommil This looks good. I'll fix this in 8.

**Comment by xuwei-k** [comment]
```
[info] Compiling 12 Scala sources to /home/travis/build/scalaz/effect/target/scala-2.12/classes ...
[error] /home/travis/build/scalaz/effect/src/main/scala/scalaz/ioeffect/RTS.scala:535:34: unreachable code
[error]                             eval = false
[error]                                  ^
[error] 5 errors found
[error] (Compile / compileIncremental) Compilation failed
```

🤔  

https://travis-ci.org/scalaz/ioeffect/builds/364861651#L515

**Comment by fommil** [comment]
@xuwei-k I have no idea what is going on there... looks like a compiler bug.

@jdegoes is the `Later` codepath covered in the tests? If so, I'll turn off the broken compiler warning.

**Comment by fommil** [comment]
I raised a bug report with scalac. I suspect a bug in the interplay between this encoding, `var` and `try` / `catch`.

If ever there was a way to start the day depressed,  I recommend discovering yet another scalac cliff edge.

**Comment by emilypi** [comment]
@fommil I was confused about that bug as well when I reviewed the code and saw that it was failing for dead code. It seemed to be a total pattern match, so i'm left wondering why it's a problem. I'd be interested to see why scalac things that's dead code.

**Comment by jbgi** [comment]
in the meantime [`@silent`](https://github.com/ghik/silencer) can be use to suppress the warning.

**Comment by hrhino** [comment]
https://github.com/fommil/effect/pull/1

**Review by hrhino — APPROVED** [review]

**Comment by hrhino** [comment]
```
src/main/scala/scalaz/ioeffect/AsyncReturn.scala:34:38: error: [DisableSyntax.covariant] Covariant types could lead to error-prone situations.
```

hahahahahahahahaha.

**Comment by fommil** [comment]
you can suppress scalafix warnings https://scalacenter.github.io/scalafix/docs/users/configuration#suppressing-rules

**Comment by fommil** [comment]
(I'll do it later)

**Pull request merged**
